Add unitests for kill() around SIGTERM handling
crusaderky/pshell pull request #6
Opened 2019-01-27 20:47 UTC by jcclin

For issue 1: Two new unit tests for kill() around SIGTERM handling.  On e test with a process (python script) that gracefully shuts down in 5s, and the other test with a process that completely ignores SIGTERM.

2019-01-27 21:09 UTC, jcclin commented
Change f-string to str.format() to accommodate py35

2019-01-27 21:28 UTC, jcclin commented
Change f-string to str.format() to accommodate py35

2019-02-01 16:22 UTC, crusaderky requested changes
Thank you very much for the contribution!
I suggested some minor tweaks.

2019-02-01 16:22 UTC, crusaderky commented on pshell/tests/data/sleep20_sigterm_delay5.py
> +    sys.exit(0)
unneeded explicit sys.exit()

2019-02-01 16:22 UTC, crusaderky commented on pshell/tests/data/sleep20_sigterm_ignore.py
> +    sys.exit(0)
unneeded explicit sys.exit() (as well as the 'import sys' at the top)

2019-02-01 16:22 UTC, crusaderky commented on pshell/tests/test_procs.py
> +    cmd = ['python', os.path.join(DATADIR, 'sleep20_sigterm_delay5.py')]
This is problematic when the desired interpreter is not in the PATH. This is actually the norm when running the test from inside PyCharm. Please replace 'python' with sys.executable.

2019-02-01 16:22 UTC, crusaderky commented on pshell/tests/test_procs.py
> +    cmd = ['python', os.path.join(DATADIR, 'sleep20_sigterm_ignore.py')]
Replace 'python' with sys.executable

2019-02-01 16:22 UTC, crusaderky commented on pshell/tests/test_procs.py
> +
single blank line please

2019-02-01 16:22 UTC, crusaderky commented on pshell/tests/test_procs.py
> +
single blank line please

2019-02-01 16:22 UTC, crusaderky commented on pshell/tests/data/sleep20_sigterm_delay5.py
> +#! /usr/bin/env python
Unidiomatic - please remove whitespace after !

2019-02-02 11:24 UTC, jcclin commented
Thank you very much for the review!
I have corrected these tweaks and re-submit again.
Please feel free to critique further.

2019-02-02 15:50 UTC, crusaderky approved these changes

2019-02-02 15:51 UTC, merged

2019-02-02 15:51 UTC, crusaderky commented
Everything looks great, thank you!
Fixes #5